### ISSUE TITLE
Use a Wikipedia-compatible open license for the data

### ISSUE THREAD

**Issue by hugolpz** [hermitdave/FrequencyWords#10]
> MIT license permits reuse [...] provided that all copies of the licensed software include a copy of the MIT License terms.

MIT license is a "non copyleft permissive license" which is adapted for software but not for data.

![sdfg](https://user-images.githubusercontent.com/1420189/40273198-44cabac0-5bbc-11e8-88c7-127b6b465265.png)

Data would be better of under a more convenient license...
Preferably Public domain.
CC-by-sa would do as well : )

**Comment by hermitdave** [comment]
Oops.. i for some reason never saw this.
Let me check this in a bit

**Comment by hermitdave** [comment]
In a bit as in today

**Comment by hugolpz** [comment]
I think i saw you migrated to CC-by-sa somewhere. I get back when i am on pc.

**Comment by hugolpz** [comment]
Note: I started to test and use your frequency list within LinguaLibre.fr, a Wikimedia project whose ojective is to audio record all words. Our project is still in Public Beta, adding sources-credit within the list's page breaks some stuff as of now. We are tracking the issue, so we can properly credit you on each list page.

* tracking the issue https://phabricator.wikimedia.org/T212671
* intended tag : https://lingualibre.fr/wiki/Template:Hermite_Dave
* current test with section "Source": https://lingualibre.fr/wiki/List:Pol/words-by-frequency-2001-to-4000#Source
* current unintended effect on Recording Studio :point_down: 
![screenshot from 2018-12-28 17-39-18](https://user-images.githubusercontent.com/1420189/50521774-91a83380-0ac7-11e9-9097-6dec0f1f1016.png) 

Lingua Libre is an open source, crowd sourced project. We do as best as we can. :strawberry:

**Comment by hugolpz** [comment]
I made a pull request. Thanks github ! https://github.com/hermitdave/FrequencyWords/pull/11

**Comment by hugolpz** [comment]
I made a pull request. Thanks github ! https://github.com/hermitdave/FrequencyWords/pull/11

**Comment by hugolpz** [comment]
Done thanks to https://github.com/hermitdave/FrequencyWords/pull/11 and https://github.com/hermitdave/FrequencyWords/commit/884c4bc4abf126265900626cbfb53a237281bb6a
