### ISSUE TITLE
Is the list compiled from the parallel subset of the corpus?

### ISSUE THREAD

**Issue by rgalhama** [hermitdave/FrequencyWords#12]
Hi @hermitdave ,
first, thanks for putting this list together! I just wanted to ask whether these words were collected from the whole database in OpenSubtitle, or only for the parallel subset. Concretely, I am working with the English and the Hebrew corpora, and it would be useful for me to know whether they were collected from the same movies.
Thanks!,

Raquel

**Comment by hermitdave** [comment]
@rgalhama the source of the open subtitles was below.
http://opus.lingfil.uu.se/OpenSubtitles2016.php

The subtitles vary per language. I never looked into this particular requirement (whether they were from same movies or not) but it can be done with some work.

Hermit

**Comment by rgalhama** [comment]
Hi @hermitdave ,

Thanks for your quick reply. After a quick comparison, I can confirm that, at least for the case of Hebrew and English, they do *not* come from the parallel subset. 

Best,

Raquel
