### ISSUE TITLE
Upgrade license to CC-BY-SA 4.0

### ISSUE THREAD

**Issue by manuelaugustin** [hermitdave/FrequencyWords#16]
Hi @hermitdave, 

Thanks for putting together these frequency lists and making them available on GitHub! We'd like to use the frequency words lists on your site for our software project. Specifically, we'd like to use them as stop words in our text analysis.

Our software project is an open-source project licensed under GPL. You can find it here: https://github.com/Yoast/javascript.

Unfortunately, the CC-BY-SA 3.0 license used for the data in your project isn't compatible with GPL. Would you perhaps consider upgrading the license of your data to a CC-BY-SA 4.0? That license is compatible with GPL, see https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses/. Alternatively, a GPL or LGPL license would also work for us.

Changing the license to CC-BY-SA 4.0 would open up the data for wider usage in open source software development, so I'm sure many others would benefit from it as well.

Best,
Manuel

**Comment by hermitdave** [comment]
Apologies for delay. Done.

**Comment by manuelaugustin** [comment]
That's great, thank you very much!
