### ISSUE TITLE
Wordlists without 50k words

### ISSUE THREAD

**Issue by atoponce** [hermitdave/FrequencyWords#3]
The following language files are named with "_50k" appended to the filename, but do not contain 50k words:

    10282 content/2016/af/af_50k.txt
     2350 content/2016/bn/bn_50k.txt
     7131 content/2016/br/br_50k.txt
    31631 content/2016/eo/eo_50k.txt
     2968 content/2016/hi/hi_50k.txt
     1972 content/2016/hy/hy_50k.txt
     3402 content/2016/kk/kk_50k.txt
     2604 content/2016/ml/ml_50k.txt
     7504 content/2016/si/si_50k.txt
      927 content/2016/ta/ta_50k.txt
     1402 content/2016/te/te_50k.txt
     6033 content/2016/tl/tl_50k.txt

**Comment by hermitdave** [comment]
@atoponce sorry I was too lazy.. I suppose I should fix this for next version.

**Comment by hugolpz** [comment]
Renaming doesnt seems critical tho. It's easy to understand these files as "first 50k items".

**Comment by hermitdave** [comment]
This has been corrected for 2018 data set.
