### ISSUE TITLE
Generate Dataset for OpenSubtitles 2018 

### ISSUE THREAD

**Issue by hermitdave** [hermitdave/FrequencyWords#9]

**Comment by hugolpz** [comment]
See http://opus.nlpl.eu/OpenSubtitles2018.php :smile:

**Comment by hermitdave** [comment]
@hugolpz apologies for the delays.. i downloaded the tar.gz files on another machine and never got around to running it. 
Based on early user feedback, I implemented checks to ensure duplicates were reduced. The subtitle folders often contain multiple subtitles. I have taken to only picking up a single file if multiple files are found. Programmatically identifying language is harder.

I could do basic checks like this language should only have latin / cryllic  character set.

**Comment by hermitdave** [comment]
I am going to use this project to do language detection
https://github.com/TechnikEmpire/language-detection

Its a .NET port of 
https://code.google.com/archive/p/language-detection/

**Comment by hugolpz** [comment]
Hello Dave, cool to see you back,
Thanks for considering my input.

> I could do basic checks like this language should only have latin / cyrillic character set.
I think you "latin/cyrillic" would mean russian and similar, as subtitles often contains latin words for all languages, at least for "ok" and other basic ones.

As for :
> I am going to use this project to do language detection
* [Java](https://code.google.com/archive/p/language-detection/) (original) : `99% over precision for 53 languages`
  * [.NET](https://github.com/TechnikEmpire/language-detection)
  * [Python](https://github.com/Mimino666/langdetect) : `supports 55 languages out of the box.`

Or [others](https://github.com/search?q=language+detect) : 
- Node [franc](https://github.com/wooorm/franc) :  `packaged with support for 82, 188, or 402 languages`

**Comment by hermitdave** [comment]
Thanks @hugolpz I have reworked the code and added language lookup using .NET for now.
Its slowly chugging along generating the files as we speak. I am downloading the dataset again - they changed from tar.gz to zip so wanted to ensure i had the latest set..

I will start uploading soon

**Comment by hugolpz** [comment]
Ahahahahahahahahaha. I didn't expected that fast :+1:

**Comment by hermitdave** [comment]
@hugolpz i am at home (case of mild flu) which means I can do other things.

That's pretty neat 👍 I force lower casing to ensure small reduction in noise

**Comment by hermitdave** [comment]
Maybe I should create another output with the words / characters that were filtered out ?

**Comment by hugolpz** [comment]
Yes, forcing lower case is smart.
For names I had to inject back the Capitalization manually. But I'am not sure it really worth it has my end goal is to record words : my recording can be all lower case as well.
